name: Get install-full-node.sh
on:   
  schedule:
     - cron: '0 12 1 * *'

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: curl https://bitnodes.io/install-full-node.sh -o install-full-node.sh

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: .
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
