name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sysctl -w net.ipv4.ip_forward=1
      - name: Build the stack
        run: docker-compose up
     # - run: sudo ifconfig
      # - run: cat /etc/sysctl.conf
     # - run: docker exec bitnodes apk update && apk add bind-tools && dig  @1.1.1.1 google.com
     # - run: docker exec bitnodes dig @2001:4860:4860::8888 google.com
 
