name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - run: sudo ifconfig
      - run: docker exec bitnodes ping -c 10 1.1.1.1
      - run: docker exec bitnodes ping -c 10 -6 2001:4860:4860::8888
