name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: sudo apt-get update -y
        run: sudo apt-get install -y libseccomp2
        run: docker-compose up
